apiVersion: v1
kind: Service
metadata:
  name: ap-service
spec:
  selector:
    app: api
  ports: 
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: snehac174/api:1
        ports:
        - containerPort: 4000
